export const PROVINCIAS_AR = [
  "Buenos Aires", "CABA", "Catamarca", "Chaco", "Chubut", "Córdoba",
  "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja",
  "Mendoza", "Misiones", "Neuquén", "Río Negro", "Salta", "San Juan",
  "San Luis", "Santa Cruz", "Santa Fe", "Santiago del Estero",
  "Tierra del Fuego", "Tucumán",
];

export const PAISES_MUNDO = [
  "Argentina", "Bolivia", "Brasil", "Chile", "Colombia", "Costa Rica",
  "Cuba", "Ecuador", "El Salvador", "Guatemala", "Honduras", "México",
  "Nicaragua", "Panamá", "Paraguay", "Perú", "República Dominicana",
  "Uruguay", "Venezuela",
  "Alemania", "Australia", "Austria", "Bélgica", "Canadá", "China",
  "Corea del Sur", "España", "Estados Unidos", "Francia", "India",
  "Israel", "Italia", "Japón", "Nueva Zelanda", "Países Bajos",
  "Polonia", "Portugal", "Reino Unido", "Rusia", "Sudáfrica",
  "Suecia", "Suiza", "Turquía", "Ucrania",
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua y Barbuda",
  "Armenia", "Azerbaijan", "Bahamas", "Bahréin", "Bangladesh", "Barbados",
  "Belarus", "Belize", "Benín", "Bután", "Bosnia y Herzegovina", "Botsuana",
  "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Camboya",
  "Camerún", "Catar", "Comoras", "Congo", "Croacia", "Chipre",
  "Dinamarca", "Djibouti", "Dominica", "Egipto", "Emiratos Árabes Unidos",
  "Eritrea", "Eslovaquia", "Eslovenia", "Estonia", "Etiopía", "Fiji",
  "Filipinas", "Finlandia", "Gabón", "Gambia", "Georgia", "Ghana",
  "Granada", "Grecia", "Guinea", "Guinea-Bisáu", "Guinea Ecuatorial",
  "Guyana", "Haití", "Hungría", "Indonesia", "Irak", "Irán",
  "Irlanda", "Islandia", "Islas Marshall", "Islas Salomón", "Jamaica",
  "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati",
  "Kosovo", "Kuwait", "Laos", "Lesoto", "Letonia", "Líbano",
  "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo",
  "Macedonia del Norte", "Madagascar", "Malasia", "Malaui", "Maldivas",
  "Mali", "Malta", "Marruecos", "Mauricio", "Mauritania", "Micronesia",
  "Moldavia", "Mónaco", "Mongolia", "Montenegro", "Mozambique",
  "Myanmar", "Namibia", "Nauru", "Nepal", "Níger", "Nigeria",
  "Noruega", "Omán", "Pakistán", "Palaos", "Palestina", "Papúa Nueva Guinea",
  "República Centroafricana", "República Checa", "República del Congo",
  "Ruanda", "Rumania", "Saint Kitts y Nevis", "Samoa", "San Marino",
  "Santa Lucía", "Santo Tomé y Príncipe", "San Vicente y las Granadinas",
  "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur",
  "Somalia", "Sri Lanka", "Sudán", "Sudán del Sur", "Surinam",
  "Suazilandia", "Tailandia", "Tanzania", "Timor Oriental", "Togo",
  "Tonga", "Trinidad y Tobago", "Túnez", "Turkmenistán", "Tuvalu",
  "Uganda", "Uzbekistán", "Vanuatu", "Vietnam", "Yemen", "Yibuti",
  "Zambia", "Zimbabue",
];
