export const PROVINCIAS_AR = [
  "Buenos Aires", "CABA", "Catamarca", "Chaco", "Chubut", "Córdoba",
  "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja",
  "Mendoza", "Misiones", "Neuquén", "Río Negro", "Salta", "San Juan",
  "San Luis", "Santa Cruz", "Santa Fe", "Santiago del Estero",
  "Tierra del Fuego", "Tucumán",
];

export const PAISES_MUNDO = [
  "Argentina", "Bolivia", "Brasil", "Chile", "Colombia", "Costa Rica",
  "Cuba", "Ecuador", "El Salvador", "Guatemala", "Honduras", "México",
  "Nicaragua", "Panamá", "Paraguay", "Perú", "República Dominicana",
  "Uruguay", "Venezuela",
  "Alemania", "Australia", "Austria", "Bélgica", "Canadá", "China",
  "Corea del Sur", "España", "Estados Unidos", "Francia", "India",
  "Israel", "Italia", "Japón", "Nueva Zelanda", "Países Bajos",
  "Polonia", "Portugal", "Reino Unido", "Rusia", "Sudáfrica",
  "Suecia", "Suiza", "Turquía", "Ucrania",
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua y Barbuda",
  "Armenia", "Azerbaijan", "Bahamas", "Bahréin", "Bangladesh", "Barbados",
  "Belarus", "Belize", "Benín", "Bután", "Bosnia y Herzegovina", "Botsuana",
  "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Camboya",
  "Camerún", "Catar", "Comoras", "Congo", "Croacia", "Chipre",
  "Dinamarca", "Djibouti", "Dominica", "Egipto", "Emiratos Árabes Unidos",
  "Eritrea", "Eslovaquia", "Eslovenia", "Estonia", "Etiopía", "Fiji",
  "Filipinas", "Finlandia", "Gabón", "Gambia", "Georgia", "Ghana",
  "Granada", "Grecia", "Guinea", "Guinea-Bisáu", "Guinea Ecuatorial",
  "Guyana", "Haití", "Hungría", "Indonesia", "Irak", "Irán",
  "Irlanda", "Islandia", "Islas Marshall", "Islas Salomón", "Jamaica",
  "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati",
  "Kosovo", "Kuwait", "Laos", "Lesoto", "Letonia", "Líbano",
  "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo",
  "Macedonia del Norte", "Madagascar", "Malasia", "Malaui", "Maldivas",
  "Mali", "Malta", "Marruecos", "Mauricio", "Mauritania", "Micronesia",
  "Moldavia", "Mónaco", "Mongolia", "Montenegro", "Mozambique",
  "Myanmar", "Namibia", "Nauru", "Nepal", "Níger", "Nigeria",
  "Noruega", "Omán", "Pakistán", "Palaos", "Palestina", "Papúa Nueva Guinea",
  "República Centroafricana", "República Checa", "República del Congo",
  "Ruanda", "Rumania", "Saint Kitts y Nevis", "Samoa", "San Marino",
  "Santa Lucía", "Santo Tomé y Príncipe", "San Vicente y las Granadinas",
  "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur",
  "Somalia", "Sri Lanka", "Sudán", "Sudán del Sur", "Surinam",
  "Suazilandia", "Tailandia", "Tanzania", "Timor Oriental", "Togo",
  "Tonga", "Trinidad y Tobago", "Túnez", "Turkmenistán", "Tuvalu",
  "Uganda", "Uzbekistán", "Vanuatu", "Vietnam", "Yemen", "Yibuti",
  "Zambia", "Zimbabue",
];

// Código de área telefónico por país (con "+"), para autocompletar el campo
// de teléfono en el registro apenas se elige el país. Las claves coinciden
// exactamente con los nombres de PAISES_MUNDO.
export const CODIGO_TELEFONICO: Record<string, string> = {
  Argentina: "+54", Bolivia: "+591", Brasil: "+55", Chile: "+56", Colombia: "+57",
  "Costa Rica": "+506", Cuba: "+53", Ecuador: "+593", "El Salvador": "+503",
  Guatemala: "+502", Honduras: "+504", México: "+52", Nicaragua: "+505",
  Panamá: "+507", Paraguay: "+595", Perú: "+51", "República Dominicana": "+1",
  Uruguay: "+598", Venezuela: "+58",
  Alemania: "+49", Australia: "+61", Austria: "+43", Bélgica: "+32", Canadá: "+1",
  China: "+86", "Corea del Sur": "+82", España: "+34", "Estados Unidos": "+1",
  Francia: "+33", India: "+91", Israel: "+972", Italia: "+39", Japón: "+81",
  "Nueva Zelanda": "+64", "Países Bajos": "+31", Polonia: "+48", Portugal: "+351",
  "Reino Unido": "+44", Rusia: "+7", Sudáfrica: "+27", Suecia: "+46", Suiza: "+41",
  Turquía: "+90", Ucrania: "+380",
  Afghanistan: "+93", Albania: "+355", Algeria: "+213", Andorra: "+376",
  Angola: "+244", "Antigua y Barbuda": "+1", Armenia: "+374", Azerbaijan: "+994",
  Bahamas: "+1", Bahréin: "+973", Bangladesh: "+880", Barbados: "+1",
  Belarus: "+375", Belize: "+501", Benín: "+229", Bután: "+975",
  "Bosnia y Herzegovina": "+387", Botsuana: "+267", Brunéi: "+673",
  Bulgaria: "+359", "Burkina Faso": "+226", Burundi: "+257", "Cabo Verde": "+238",
  Camboya: "+855", Camerún: "+237", Catar: "+974", Comoras: "+269", Congo: "+242",
  Croacia: "+385", Chipre: "+357", Dinamarca: "+45", Djibouti: "+253",
  Dominica: "+1", Egipto: "+20", "Emiratos Árabes Unidos": "+971", Eritrea: "+291",
  Eslovaquia: "+421", Eslovenia: "+386", Estonia: "+372", Etiopía: "+251",
  Fiji: "+679", Filipinas: "+63", Finlandia: "+358", Gabón: "+241", Gambia: "+220",
  Georgia: "+995", Ghana: "+233", Granada: "+1", Grecia: "+30", Guinea: "+224",
  "Guinea-Bisáu": "+245", "Guinea Ecuatorial": "+240", Guyana: "+592",
  Haití: "+509", Hungría: "+36", Indonesia: "+62", Irak: "+964", Irán: "+98",
  Irlanda: "+353", Islandia: "+354", "Islas Marshall": "+692",
  "Islas Salomón": "+677", Jamaica: "+1", Jordania: "+962", Kazajistán: "+7",
  Kenia: "+254", Kirguistán: "+996", Kiribati: "+686", Kosovo: "+383",
  Kuwait: "+965", Laos: "+856", Lesoto: "+266", Letonia: "+371", Líbano: "+961",
  Liberia: "+231", Libia: "+218", Liechtenstein: "+423", Lituania: "+370",
  Luxemburgo: "+352", "Macedonia del Norte": "+389", Madagascar: "+261",
  Malasia: "+60", Malaui: "+265", Maldivas: "+960", Mali: "+223", Malta: "+356",
  Marruecos: "+212", Mauricio: "+230", Mauritania: "+222", Micronesia: "+691",
  Moldavia: "+373", Mónaco: "+377", Mongolia: "+976", Montenegro: "+382",
  Mozambique: "+258", Myanmar: "+95", Namibia: "+264", Nauru: "+674",
  Nepal: "+977", Níger: "+227", Nigeria: "+234", Noruega: "+47", Omán: "+968",
  Pakistán: "+92", Palaos: "+680", Palestina: "+970",
  "Papúa Nueva Guinea": "+675", "República Centroafricana": "+236",
  "República Checa": "+420", "República del Congo": "+243", Ruanda: "+250",
  Rumania: "+40", "Saint Kitts y Nevis": "+1", Samoa: "+685",
  "San Marino": "+378", "Santa Lucía": "+1", "Santo Tomé y Príncipe": "+239",
  "San Vicente y las Granadinas": "+1", Senegal: "+221", Serbia: "+381",
  Seychelles: "+248", "Sierra Leona": "+232", Singapur: "+65", Somalia: "+252",
  "Sri Lanka": "+94", Sudán: "+249", "Sudán del Sur": "+211", Surinam: "+597",
  Suazilandia: "+268", Tailandia: "+66", Tanzania: "+255",
  "Timor Oriental": "+670", Togo: "+228", Tonga: "+676",
  "Trinidad y Tobago": "+1", Túnez: "+216", Turkmenistán: "+993",
  Tuvalu: "+688", Uganda: "+256", Uzbekistán: "+998", Vanuatu: "+678",
  Vietnam: "+84", Yemen: "+967", Yibuti: "+253", Zambia: "+260",
  Zimbabue: "+263",
};
